//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissionInforLeader
    {
        public System.Guid MisionId { get; set; }
        public string GroupName { get; set; }
        public string GroupInfor { get; set; }
        public string LeaderStaff { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual MissionMember MissionMember { get; set; }
        public virtual Mission Mission { get; set; }
    }
}
