//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SEP23Team7Entities : DbContext
    {
        public SEP23Team7Entities()
            : base("name=SEP23Team7Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<MissionInforLeader> MissionInforLeaders { get; set; }
        public virtual DbSet<MissionMember> MissionMembers { get; set; }
        public virtual DbSet<Mission> Missions { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<UserOfMission> UserOfMissions { get; set; }
        public virtual DbSet<UsersOfDepartment> UsersOfDepartments { get; set; }
    }
}
