//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notify
    {
        public int Id { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string Content { get; set; }
        public string AssignFrom { get; set; }
        public string AssignTo { get; set; }
        public bool IsRead { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string TaskName { get; set; }
        public string AssignFromFullName { get; set; }
        public string AssignToFullName { get; set; }
        public string ChangeBy { get; set; }
        public string ChangeByFullName { get; set; }
        public Nullable<int> UserNorifyId { get; set; }
    }
}
