//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Task1 = new HashSet<Task>();
            this.WorkOfFiles = new HashSet<WorkOfFile>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Assignedto { get; set; }
        public System.DateTime DayCreated { get; set; }
        public System.DateTime DayEnd { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserId { get; set; }
        public System.DateTime DayStart { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> MissionId { get; set; }
        public Nullable<System.Guid> SubTaskId { get; set; }
        public string Acceptance { get; set; }
        public Nullable<int> Proportion { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual MissionMember MissionMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Task1 { get; set; }
        public virtual Task Task2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOfFile> WorkOfFiles { get; set; }
    }
}
