//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotify
    {
        public int Id { get; set; }
        public Nullable<int> NotifyId { get; set; }
        public string AssignFrom { get; set; }
        public string AssignTo { get; set; }
        public bool IsRead { get; set; }
        public string UserId { get; set; }
        public Nullable<int> OrderId { get; set; }
    }
}
