//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOfFile
    {
        public Nullable<System.Guid> TaskId { get; set; }
        public Nullable<System.Guid> FileId { get; set; }
        public System.Guid WOFId { get; set; }
    
        public virtual FileAttachment FileAttachment { get; set; }
        public virtual Task Task { get; set; }
    }
}
